### ISSUE TITLE
No map size limit

### ISSUE THREAD

**Issue by JeremieBourque1** [introlab/opentera-webrtc-ros#26]
Right now, when the map grows out of bounds of the generated map image, the map stops being able to be drawn. Ideally, the map image generator should be able to crop the parts of the map hat are outside of the image.
Changes will probably have to be made in `OccupancyGridImageDrawer.cpp`

**Comment by doumdi** [comment]
The idea is to make a portion of the map (depending of the scale factor) available. The new implementation should act like a GPS navigation map, with the robot in the center of the map, map top in the robot's orientation. This would enable to see the surroundings of the robot and the laser scan to avoid nearby obstacles.
