### ISSUE TITLE
Handle Video Reception Properly in StreamBridge.cpp for topic_streamer

### ISSUE THREAD

**Issue by doumdi** [introlab/opentera-webrtc-ros#3]
VideoSink should be replaced by callback : 

void StreamClient::setOnVideoFrameReceived(
        const std::function<void(const Client&, const cv::Mat& bgrImg, uint64_t timestampUs)>& callback)

https://github.com/introlab/opentera-webrtc-teleop/blob/93afd6187b9d54aa5306aa78789de5e7192cac82/opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/StreamClient.h#L120

**Comment by G-Lauz** [comment]
Work in progress in [opentera-webrtc-ros-dev](https://github.com/introlab/opentera-webrtc-ros/tree/opentera-webrtc-ros-dev) branch
