### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by JNimkar** [introlab/opentera-webrtc-ros#4]
Hi, 

I am trying to build this package in my catkin workspace and I'm getting the following error: 

`CMake Error at opentera-webrtc-ros/CMakeLists.txt:9 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".`

I am using cmake version **3.10.2**

**Comment by doumdi** [comment]
This package will only work on Ubuntu 20.04 for now with ROS Noetic. It seems that add_compile_definitions was added in [CMake 3.12](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html).
