### ISSUE TITLE
Add ROS messages to convert OpenTera events to ROS messages that will be used by CPP and python clients.

### ISSUE THREAD

**Issue by doumdi** [introlab/opentera-webrtc-ros#7]
Messages are "bridged" with protobuf JSON messages, from [opentera-messages](https://github.com/introlab/opentera_messages) package.

**Comment by doumdi** [comment]
See opentera-client-ros branch.

**Comment by doumdi** [comment]
Streamers should receive events and join sessions.

**Comment by G-Lauz** [comment]
Work in progress in [opentera-webrtc-ros-dev](https://github.com/introlab/opentera-webrtc-ros/tree/opentera-webrtc-ros-dev) branch
